#!/bin/bash

set -xv

if hash docker; then
  echo "Docker is installed"
else
  apk --update add docker
fi

MEDIA=/home/pi/media
FILEBOT="docker run --rm -v /home/pi/torrents-config/scripts:/scripts -v $MEDIA:$MEDIA -v /home/pi/downloads/incoming:/downloads/incoming pablokbs/filebot-rpi"
MOVIES="$MEDIA/peliculas"
SERIES="$MEDIA/series"
MOVIES_FORMAT="movieFormat=$MOVIES/{n} ({y})/{n} ({y})"
SERIES_FORMAT="seriesFormat=$SERIES/{n}/{'Season '+s}/{n} - {s00e00}"
ARG_PATH="$1"
ARG_LABEL="$2"

if [ $ARG_LABEL == 'juegos' ]
then
  exit 0
fi

$FILEBOT -script fn:amc \
  --output "$MEDIA" \
  --action copy \
  --conflict skip \
  -non-strict \
  --def "$MOVIES_FORMAT" "$SERIES_FORMAT" \
  --def minFileSize=0 \
  ut_dir="$ARG_PATH" \
  ut_kind="multi"
